import type { CardDef } from './types';

export const CARDS: Record<string, CardDef> = {
  strike: {
    id: 'strike',
    name: 'Hearthblade',
    type: 'Attack',
    cost: 1,
    rarity: 'basic',
    description: 'Deal 6 damage.',
    damage: 6,
  },
  strike_plus: {
    id: 'strike_plus',
    name: 'Hearthblade+',
    type: 'Attack',
    cost: 1,
    rarity: 'basic',
    description: 'Deal 9 damage.',
    damage: 9,
    upgraded: true,
    upgradeOf: 'strike',
  },
  defend: {
    id: 'defend',
    name: 'Shield Oath',
    type: 'Skill',
    cost: 1,
    rarity: 'basic',
    description: 'Gain 5 Block.',
    block: 5,
  },
  defend_plus: {
    id: 'defend_plus',
    name: 'Shield Oath+',
    type: 'Skill',
    cost: 1,
    rarity: 'basic',
    description: 'Gain 8 Block.',
    block: 8,
    upgraded: true,
    upgradeOf: 'defend',
  },
  bash: {
    id: 'bash',
    name: 'Crown Bash',
    type: 'Attack',
    cost: 2,
    rarity: 'basic',
    description: 'Deal 8 damage. Apply 2 Vulnerable.',
    damage: 8,
    vulnerable: 2,
  },
  bash_plus: {
    id: 'bash_plus',
    name: 'Crown Bash+',
    type: 'Attack',
    cost: 2,
    rarity: 'basic',
    description: 'Deal 10 damage. Apply 3 Vulnerable.',
    damage: 10,
    vulnerable: 3,
    upgraded: true,
    upgradeOf: 'bash',
  },
  flame_burst: {
    id: 'flame_burst',
    name: 'Twin Cinders',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 4 damage twice.',
    damage: 4,
    hits: 2,
  },
  flame_burst_plus: {
    id: 'flame_burst_plus',
    name: 'Twin Cinders+',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 6 damage twice.',
    damage: 6,
    hits: 2,
    upgraded: true,
    upgradeOf: 'flame_burst',
  },
  iron_will: {
    id: 'iron_will',
    name: 'Iron Oath',
    type: 'Skill',
    cost: 1,
    rarity: 'common',
    description: 'Gain 7 Block.',
    block: 7,
  },
  iron_will_plus: {
    id: 'iron_will_plus',
    name: 'Iron Oath+',
    type: 'Skill',
    cost: 1,
    rarity: 'common',
    description: 'Gain 10 Block.',
    block: 10,
    upgraded: true,
    upgradeOf: 'iron_will',
  },
  ember_shield: {
    id: 'ember_shield',
    name: 'Flameward',
    type: 'Skill',
    cost: 1,
    rarity: 'common',
    description: 'Gain 5 Block. Draw 1 card.',
    block: 5,
    draw: 1,
  },
  ember_shield_plus: {
    id: 'ember_shield_plus',
    name: 'Flameward+',
    type: 'Skill',
    cost: 1,
    rarity: 'common',
    description: 'Gain 8 Block. Draw 1 card.',
    block: 8,
    draw: 1,
    upgraded: true,
    upgradeOf: 'ember_shield',
  },
  ignite: {
    id: 'ignite',
    name: 'Kindle Fury',
    type: 'Power',
    cost: 1,
    rarity: 'uncommon',
    description: 'Gain 2 Strength.',
    strength: 2,
  },
  ignite_plus: {
    id: 'ignite_plus',
    name: 'Kindle Fury+',
    type: 'Power',
    cost: 1,
    rarity: 'uncommon',
    description: 'Gain 3 Strength.',
    strength: 3,
    upgraded: true,
    upgradeOf: 'ignite',
  },
  cinder_slash: {
    id: 'cinder_slash',
    name: 'Cinder Cut',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 9 damage.',
    damage: 9,
  },
  cinder_slash_plus: {
    id: 'cinder_slash_plus',
    name: 'Cinder Cut+',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 12 damage.',
    damage: 12,
    upgraded: true,
    upgradeOf: 'cinder_slash',
  },
  inferno: {
    id: 'inferno',
    name: 'Hearthstorm',
    type: 'Attack',
    cost: 2,
    rarity: 'uncommon',
    description: 'Deal 7 damage to ALL enemies.',
    aoeDamage: 7,
  },
  inferno_plus: {
    id: 'inferno_plus',
    name: 'Hearthstorm+',
    type: 'Attack',
    cost: 2,
    rarity: 'uncommon',
    description: 'Deal 10 damage to ALL enemies.',
    aoeDamage: 10,
    upgraded: true,
    upgradeOf: 'inferno',
  },
  ash_armor: {
    id: 'ash_armor',
    name: 'Ashen Plate',
    type: 'Skill',
    cost: 2,
    rarity: 'uncommon',
    description: 'Gain 12 Block.',
    block: 12,
  },
  ash_armor_plus: {
    id: 'ash_armor_plus',
    name: 'Ashen Plate+',
    type: 'Skill',
    cost: 2,
    rarity: 'uncommon',
    description: 'Gain 16 Block.',
    block: 16,
    upgraded: true,
    upgradeOf: 'ash_armor',
  },
  burning_blade: {
    id: 'burning_blade',
    name: 'Living Brand',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 7 damage. Gain 1 Strength.',
    damage: 7,
    strength: 1,
  },
  burning_blade_plus: {
    id: 'burning_blade_plus',
    name: 'Living Brand+',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 9 damage. Gain 1 Strength.',
    damage: 9,
    strength: 1,
    upgraded: true,
    upgradeOf: 'burning_blade',
  },
  smolder: {
    id: 'smolder',
    name: 'Smolder Step',
    type: 'Skill',
    cost: 0,
    rarity: 'common',
    description: 'Gain 4 Block. Draw 1 card.',
    block: 4,
    draw: 1,
  },
  smolder_plus: {
    id: 'smolder_plus',
    name: 'Smolder Step+',
    type: 'Skill',
    cost: 0,
    rarity: 'common',
    description: 'Gain 6 Block. Draw 1 card.',
    block: 6,
    draw: 1,
    upgraded: true,
    upgradeOf: 'smolder',
  },
  rune_of_wrath: {
    id: 'rune_of_wrath',
    name: 'Oath of Wrath',
    type: 'Power',
    cost: 2,
    rarity: 'rare',
    description: 'Gain 3 Strength.',
    strength: 3,
  },
  rune_of_wrath_plus: {
    id: 'rune_of_wrath_plus',
    name: 'Oath of Wrath+',
    type: 'Power',
    cost: 1,
    rarity: 'rare',
    description: 'Gain 3 Strength.',
    strength: 3,
    upgraded: true,
    upgradeOf: 'rune_of_wrath',
  },
  scorch: {
    id: 'scorch',
    name: 'Brand',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 5 damage. Apply 1 Vulnerable.',
    damage: 5,
    vulnerable: 1,
  },
  scorch_plus: {
    id: 'scorch_plus',
    name: 'Brand+',
    type: 'Attack',
    cost: 1,
    rarity: 'common',
    description: 'Deal 7 damage. Apply 2 Vulnerable.',
    damage: 7,
    vulnerable: 2,
    upgraded: true,
    upgradeOf: 'scorch',
  },
  phoenix_guard: {
    id: 'phoenix_guard',
    name: 'Phoenix Vigil',
    type: 'Skill',
    cost: 1,
    rarity: 'uncommon',
    description: 'Gain 8 Block. Heal 2 HP.',
    block: 8,
    heal: 2,
  },
  phoenix_guard_plus: {
    id: 'phoenix_guard_plus',
    name: 'Phoenix Vigil+',
    type: 'Skill',
    cost: 1,
    rarity: 'uncommon',
    description: 'Gain 10 Block. Heal 4 HP.',
    block: 10,
    heal: 4,
    upgraded: true,
    upgradeOf: 'phoenix_guard',
  },
  soulfire: {
    id: 'soulfire',
    name: 'Soulfire',
    type: 'Attack',
    cost: 0,
    rarity: 'uncommon',
    description: 'Deal 3 damage. Gain 1 Energy.',
    damage: 3,
    energyGain: 1,
  },
  soulfire_plus: {
    id: 'soulfire_plus',
    name: 'Soulfire+',
    type: 'Attack',
    cost: 0,
    rarity: 'uncommon',
    description: 'Deal 5 damage. Gain 1 Energy.',
    damage: 5,
    energyGain: 1,
    upgraded: true,
    upgradeOf: 'soulfire',
  },
  ash_curse: {
    id: 'ash_curse',
    name: 'Ash Curse',
    type: 'Skill',
    cost: 1,
    rarity: 'basic',
    description: 'Unplayable. A blight on your deck.',
    curse: true,
  },
};

export const STARTER_DECK_IDS = [
  'strike',
  'strike',
  'strike',
  'strike',
  'defend',
  'defend',
  'defend',
  'defend',
  'bash',
  'flame_burst',
];

/** Reward pool (non-upgraded non-basic preferred, but basics ok too) */
export const REWARD_POOL_IDS = [
  'flame_burst',
  'iron_will',
  'ember_shield',
  'ignite',
  'cinder_slash',
  'inferno',
  'ash_armor',
  'burning_blade',
  'smolder',
  'rune_of_wrath',
  'scorch',
  'phoenix_guard',
  'soulfire',
  'bash',
];

export function getCard(id: string): CardDef {
  const card = CARDS[id];
  if (!card) throw new Error(`Unknown card: ${id}`);
  return card;
}

export function getUpgradeId(defId: string): string | null {
  const card = CARDS[defId];
  if (!card || card.upgraded) return null;
  const plus = `${defId}_plus`;
  return CARDS[plus] ? plus : null;
}

export function cardNeedsTarget(def: CardDef): boolean {
  return !!(def.damage || def.vulnerable) && !def.aoeDamage;
}
