/** Cinder Crown flavor. */
export const Flavor = {
  title: "CINDER CROWN",
  subtitle: "Ashbound",
  tagline: "The last living flame",
  blurb: "Disgraced knight. The usurper burned the sacred hearth. Carry the last living flame and reclaim the Cinder Crown.",
  playerName: "Disgraced Knight",
  begin: "Take Up the Flame",
  mapTitle: "The Ashen March",
  mapHint: "Pick your road. Higher Crowns burn hotter.",
  rewardsTitle: "Spoils of War",
  rewardsHint: "Bind a brand — or pass.",
  restTitle: "Wayside Hearth",
  restHint: "Heal, or temper a brand in living fire.",
  treasureTitle: "War Chest",
  treasureHint: "Claim gold, or double-or-nothing.",
  wagerTitle: "Ember Wager",
  wagerHint: "Stake gold on fortune. Win a brand, jackpot, or bust.",
  titheTitle: "Blood Tithe",
  titheHint: "Offer HP to the flame for power — or bleed for nothing.",
  stallTitle: "Cursed Stall",
  stallHint: "Pay the peddler. Roll a rare brand, a curse, or smoke.",
  upgradeTitle: "Temper a Brand",
  upgradeHint: "Feed a card to the living flame.",
  victoryTitle: "THE CROWN RECLAIMED",
  victoryBlurb: "The Ash Warden falls. The living flame returns. A harder Crown unlocks.",
  defeatTitle: "THE FLAME FALTERS",
  defeatBlurb: "You fall. The flame gutters — but is not gone. Crowns stay unlocked.",
  difficultyLabel: "Crown",
  node: { combat: "Skirmish", elite: "Champion", rest: "Hearth", treasure: "Chest", boss: "Ash Warden", wager: "Ember Wager", tithe: "Blood Tithe", stall: "Cursed Stall" } as const,
};
